### ISSUE TITLE
Unexpected token # in JSON at position 0

### ISSUE THREAD

**Issue by quack3d** [biofects/Google-Home-Messages#3]
I try to run the following:

curl -d '{"text":"hello", "ipaddress":"10.0.0.200", "token":"jabbadabbadu"}' -H "Content-Type: application/json" -X POST http://10.0.0.5:8092/google-home-messages

I get this error:

`SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\body-parser\lib\types\json.js:157:10)
    at parse (C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\username\Downloads\Google-Home-Messages-master\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)`

**Comment by biofects** [comment]
Hello, 
I need to set up a windows vm today, from my linux server I cannot reproduce the error

```
curl -d '{"text":"Hello, Lee. Have a nice day","ipaddress":"192.168.1.26","token":"hejd%ya83!!"}' -H "Content-Type: application/json" -X POST http://192.168.1.113:8092/google-home-messages
192.168.1.26 will say: Hello, Lee. Have a nice day.
```

**Comment by quack3d** [comment]
Tried running it on on a RPI and it seems to have worked (not home atm). Reponse was '10.0.0.5 will say: hello'. Hope you'll find a way for me to run it from Windows. :)

**Comment by quack3d** [comment]
Found the solution. In Windows Powershell I have to do this:

`curl -d '{\"text\":\"hello\", \"ipaddress\":\"10.0.0.200\", \"token\":\"jabbadabbadu\"}' -H "Content-Type: application/json" -X POST http://10.0.0.5:8092/google-home-messages`

And in cmd.exe I have to do this:

`curl -d "{\"text\":\"hello\", \"ipaddress\":\"10.0.0.200\", \"token\":\"jabbadabbadu\"}" -H "Content-Type: application/json" -X POST http://10.0.0.5:8092/google-home-messages`

Note the single quotes vs double quotes. Stupid Windows...

**Comment by biofects** [comment]
Right on, thanks for the info. I will update the README with your find.

**Comment by quack3d** [comment]
I just saw that the text editor here removed all the `\` in my comment above. I've edited it now and used "Insert code" to show how the Curl needs to be in Windows, including backslashes. Please update wiki with that info. :)

**Comment by biofects** [comment]
Thanks added to README
